Deeplink Integration
UCSD/campus-mobile pull request #1192
Opened 2021-01-23 01:27 UTC by gmihir

## Summary

The mobile app did could not be launched from an external application.

## Changelog

[General] [Add] - Add deeplinking support for iOS and Android
[General] [Add] - Added deeplink support for executing a custom search query for the maps tab
[General] [Add] - Transition to map tab if a certain class of deeplink queries is executed (deeplinking.searchmap)
[General] [Add] - Listener if a deeplink has been received

## Test Plan

Tested on iOS and Android by creating dummy web page that linked to "campusmobile://deeplinking.searchmap?query=covid". Clicking on this link caused the UC San Diego mobile app to open to the maps tab where the query had already been searched for. This query can be changed to include any search query. **Note:** Only when clicking on the deeplink from an in-app Safari ViewController (iOS only), the expected behavior happens *underneath* the VC. When the user closes the in-app safari view, they will be at the maps tab as expected.

2021-01-29 01:35 UTC, sramcode commented
I tested using the apk download for android. For iOS, the build was unavailable on TestFlight, so I pulled a PR branch that Charles created that had experimental merged with it: https://github.com/c3bryant/campus-mobile/pull/new/pr-1192-testing


Dummy webpage for deeplinking (links to covid test, parking, Geisel): https://mobile.ucsd.edu/replatform/v1/qa/webview/mihir-test/dummy_deeplink.html


**Notes on Android and iOS:**

_Deep linking/maps search only occurs when user has app open to the home tab._

- If user is on the maps, notification, or profile tab of app, clicking on the dummy webpage link does not perform search on query, but rather the app just stays in the same state as before the link was clicked. 

ex) if user has 'covid test kits' searched up on maps tab, if they click the link to direct to 'parking' on dummy webpage, then the user gets taken to the app, however it remains in the previous state of the 'covid test kits' search (no new search performed).

ex) if user has the notifications tab open, and clicks link to direct to 'parking' on webpage, then user is brought back to the notifications page and no search occurs.

- If the app is completely closed, clicking on the link causes app to open and stay on home tab without any searches.


**Notes only on iOS:**

- Logout using profile tab causes this error and webview doesn't show up on app: 

A non-null String must be provided to a Text widget.
'package:flutter/src/widgets/text.dart':
Failed assertion: line 370 pos 10: 'data != null'
The relevant error-causing widget was: 
  WebViewContainer file:///Users/sonikaram/development/campus-mobile/lib/ui/home/home.dart:154:13

2021-01-29 01:50 UTC, c3bryant requested changes
A few issues were reported on this PR. Sending it back for review/fix.

2021-02-04 00:15 UTC, gmihir commented
The app should now receive deeplinks from all views in the app (home, maps, notifications, and profile). I tested this extensively in a iOS simulator and on-device for Android (Samsung Galaxy S6). 

As far as the iOS-specific profile logout issue, I was not able to reproduce this in a simulator or on-device. 

The changes to the PR should be ready for further testing.

2021-02-22 20:59 UTC, c3bryant approved these changes

2021-02-22 20:59 UTC, merged