Add scroll position saving
UCSD/campus-mobile pull request #2019
Opened 2024-02-05 18:49 UTC by tkiyohar

## Summary

-- Reimplementation of previous PR that was wrongly repealed: "Add scroll position saving #1935" --
-- Additionally includes some code changes and improvements to original code --
Adds scroll position saving to the Home and Notifications app screens.
## Changelog

[General] [Add] - Adds scroll position saving to home and notifications pages (also includes code from Gradle update PR: "Update Gradle Version and Settings #2017")

## Test Plan

Test the home page and notifications page for any bugs and to see if their scroll position is maintained when switching between screens using the bottom nav bar after messing around on either screen (e.g., hiding or unhiding cards on the home screen from either the home screen itself or the profile screen, toggling "I'm going" on certain free food events, etc). 

Also test logging in and out of student, guest and employee accounts to make sure the scroll position on both the home and notifications pages are reset when logging in/out of an account.

If this PR is successful, the scroll position should be seamlessly saved on the notifications and home screens without any jumpy behavior when reloading these screens and no other behavior of the app should be affected.

2024-03-05 23:27 UTC, c3bryant commented on lib/core/providers/user.dart
> +import '../../ui/home/home.dart';
TODO (later): Refactor scroll controller reset methods to campus mobile core

2024-03-05 23:29 UTC, c3bryant commented on lib/core/providers/cards.dart
> +    if ((card == "student_health_wellbeing" || card == "student_info" || card == "campus_info") && _cardStates![card]!) {
Explore dynamically applying resetCardHeight

2024-03-05 23:30 UTC, c3bryant requested changes, later dismissed
Explore dynamically applying resetCardHeight in cards provider

2024-09-25 23:49 UTC, morebytes approved these changes
Looks good, fully tested

2024-09-25 23:57 UTC, merged